"""init

Revision ID: 8db18fe56683
Revises: 
Create Date: 2023-12-09 15:16:54.089323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db18fe56683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_rating_other_site', sa.Float(), nullable=False),
    sa.Column('user_rating', sa.Float(), nullable=False),
    sa.Column('type_component', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specifications', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['type_component'], ['type_component.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_table_pc_component',
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pc.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_table_pc_component')
    op.drop_table('component')
    op.drop_table('type_component')
    op.drop_table('pc')
    # ### end Alembic commands ###
