"""add id in type_component

Revision ID: 725f2111bd47
Revises: 49c61affb29c
Create Date: 2023-12-09 15:00:14.473533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725f2111bd47'
down_revision: Union[str, None] = '49c61affb29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_component', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'type_component', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_component', type_='unique')
    op.drop_column('type_component', 'id')
    # ### end Alembic commands ###
